### ISSUE TITLE
Cavas is not responsive.

### ISSUE THREAD

**Issue by Chensokheng** [ninjahatodi1/canvas#4]
Hii. I have noticed that the canvas is not responsive when we resize the screen.

@ninjahatodi1 I would like to working on this and can I make a PR for this issue?

<img width="1371" alt="Screen Shot 2020-10-06 at 11 06 42 AM" src="https://user-images.githubusercontent.com/52232579/95157729-1909f700-07c4-11eb-8498-f5402c883df2.png">
<img width="384" alt="Screen Shot 2020-10-06 at 11 09 26 AM" src="https://user-images.githubusercontent.com/52232579/95157880-7140f900-07c4-11eb-9e68-a81050fe6e96.png">

**Comment by ninjahatodi1** [comment]
Yeah sure, go for it.
